-- Creación de la tabla maestra FACULTAD
CREATE TABLE FACULTAD (
    IDFACULTAD INT,
    DESCFACULTAD VARCHAR(100),
    FECHAREGISTRO DATE
);
ALTER TABLE FACULTAD ADD CONSTRAINT FACULTAD_PK PRIMARY KEY (IDFACULTAD);

-- Crear secuencia incrementable FACULTAD
CREATE SEQUENCE INCREFACULTAD
START WITH 1
INCREMENT BY 1;

-- Crear disparador incrementable en la tabla FACULTAD
CREATE TRIGGER IDFACUL
BEFORE INSERT ON FACULTAD
FOR EACH ROW
BEGIN
SELECT INCREFACULTAD.NEXTVAL INTO :NEW.IDFACULTAD FROM DUAL;
END;
/

-- Creación de la tabla transaccional ESCUELA
CREATE TABLE ESCUELA (
    IDESCUELA INT NOT NULL,
    IDFACULTAD INT,
    NOMBRE VARCHAR2(100) NOT NULL,
    CANTALUMNOS INT NOT NULL,
    RECURSOFISCAL DECIMAL,
    LICENCIADA CHAR(1),
    CLASIFICACION INT NOT NULL,
    FECHAREGISTRO DATE
);
ALTER TABLE ESCUELA ADD CONSTRAINT ESCUELA_PK PRIMARY KEY (IDESCUELA);

-- Crear secuencia incrementable ESCUELA
CREATE SEQUENCE INCREESCUELA
START WITH 1
INCREMENT BY 1;

-- Crear disparador incrementable en la tabla ESCUELA
CREATE TRIGGER IDESCU
BEFORE INSERT ON ESCUELA
FOR EACH ROW
BEGIN
SELECT INCREESCUELA.NEXTVAL INTO :NEW.IDESCUELA FROM DUAL;
END;
/

-- Relacionando la tabla ESCUELA con FACULTAD
ALTER TABLE ESCUELA ADD CONSTRAINT ESCUELA_FACULTAD_FK FOREIGN KEY (IDFACULTAD)
    REFERENCES FACULTAD (IDFACULTAD);
    
-- Insetar registros en la tabla FACULTAD
INSERT INTO FACULTAD (DESCFACULTAD, FECHAREGISTRO) VALUES ('Facultad de Arquitectura','11-01-2022');
INSERT INTO FACULTAD (DESCFACULTAD, FECHAREGISTRO) VALUES ('Facultad de Artes y Diseño','12-01-2022');
INSERT INTO FACULTAD (DESCFACULTAD, FECHAREGISTRO) VALUES ('Facultad de Ciencias','13-01-2022');
INSERT INTO FACULTAD (DESCFACULTAD, FECHAREGISTRO) VALUES ('Facultad de Ciencias Políticas y Sociales','14-01-2022');
INSERT INTO FACULTAD (DESCFACULTAD, FECHAREGISTRO) VALUES ('Facultad de Contaduría y Administración','15-01-2022');

INSERT INTO ESCUELA (IDFACULTAD, NOMBRE, CANTALUMNOS, RECURSOFISCAL, LICENCIADA, CLASIFICACION, FECHAREGISTRO) 
VALUES (1, 'Universidad Peruana de Ciencias Aplicadas', 3000, 15000.00, 'S', 3, '16-01-2022');
INSERT INTO ESCUELA (IDFACULTAD, NOMBRE, CANTALUMNOS, RECURSOFISCAL, LICENCIADA, CLASIFICACION, FECHAREGISTRO) 
VALUES (2, 'Universidad de Lima', 4000, 16000.00, 'S', 6, '17-01-2022');
INSERT INTO ESCUELA (IDFACULTAD, NOMBRE, CANTALUMNOS, RECURSOFISCAL, LICENCIADA, CLASIFICACION, FECHAREGISTRO) 
VALUES (3, 'Universidad Ricardo Palma', 4200, 16500.00, 'S', 4, '18-01-2022');
INSERT INTO ESCUELA (IDFACULTAD, NOMBRE, CANTALUMNOS, RECURSOFISCAL, LICENCIADA, CLASIFICACION, FECHAREGISTRO) 
VALUES (4, 'Universidad Nacional de Ingeniería', 6000, 20000.00, 'N', 1, '19-01-2022');
INSERT INTO ESCUELA (IDFACULTAD, NOMBRE, CANTALUMNOS, RECURSOFISCAL, LICENCIADA, CLASIFICACION, FECHAREGISTRO) 
VALUES (5, 'Universidad César Vallejo', 3500, 14600.00, 'N', 7, '20-01-2022');